### ISSUE TITLE
SMTPDataError: (354, 'End data with <CR><LF>.<CR><LF>')

### ISSUE THREAD

**Issue by axd1967** [OnroerendErfgoed/oe_utils#163]
```
2019-08-23 09:29:59,169 ERROR [proces_notas_daemon][MainThread] (354, 'End data with <CR><LF>.<CR><LF>')
Traceback (most recent call last):
  File "/var/projects/notas/venv/local/lib/python2.7/site-packages/oe_daemonutils/controller.py", line 101, in run_daemon
    self._check_entries()
  File "/var/projects/notas/venv/local/lib/python2.7/site-packages/oe_daemonutils/controller.py", line 81, in _check_entries
    notifier.notify(notifications_dict)
  File "/var/projects/notas/venv/local/lib/python2.7/site-packages/notas_daemon/notification.py", line 44, in notify
    cc=cc_list
  File "/var/projects/notas/venv/local/lib/python2.7/site-packages/oe_utils/email/smtp.py", line 70, in send_mail
    self.smtp_obj.sendmail(self.sender, receivers + cc + bcc, msg.as_string())
  File "/usr/lib/python2.7/smtplib.py", line 751, in sendmail
    raise SMTPDataError(code, resp)
SMTPDataError: (354, 'End data with <CR><LF>.<CR><LF>')
2019-08-23 09:29:59,169 ERROR [proces_notas_daemon][MainThread] (354, 'End data with <CR><LF>.<CR><LF>')
Traceback (most recent call last):
  File "/var/projects/notas/venv/local/lib/python2.7/site-packages/oe_daemonutils/controller.py", line 101, in run_daemon
    self._check_entries()
  File "/var/projects/notas/venv/local/lib/python2.7/site-packages/oe_daemonutils/controller.py", line 81, in _check_entries
    notifier.notify(notifications_dict)
  File "/var/projects/notas/venv/local/lib/python2.7/site-packages/notas_daemon/notification.py", line 44, in notify
    cc=cc_list
  File "/var/projects/notas/venv/local/lib/python2.7/site-packages/oe_utils/email/smtp.py", line 70, in send_mail
    self.smtp_obj.sendmail(self.sender, receivers + cc + bcc, msg.as_string())
  File "/usr/lib/python2.7/smtplib.py", line 751, in sendmail
    raise SMTPDataError(code, resp)
SMTPDataError: (354, 'End data with <CR><LF>.<CR><LF>')
Process Process-11959:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/var/projects/notas/venv/local/lib/python2.7/site-packages/oe_daemonutils/controller.py", line 105, in run_daemon
    raise ex
SMTPDataError: (354, 'End data with <CR><LF>.<CR><LF>')
Processing entry https://id.erfgoed.net/archeologie/archeologienotas/12128
2019-08-23 09:29:59,177 ERROR [proces_notas_daemon][MainThread] unrecoverable error
2019-08-23 09:29:59,177 ERROR [proces_notas_daemon][MainThread] unrecoverable error
2019-08-23 09:29:59,178 ERROR [proces_notas_daemon][MainThread] processing failed
Traceback (most recent call last):
  File "/var/projects/notas/venv/local/lib/python2.7/site-packages/oe_daemonutils/controller.py", line 124, in run
    self._subprocess_daemon()
  File "/var/projects/notas/venv/local/lib/python2.7/site-packages/oe_daemonutils/controller.py", line 115, in _subprocess_daemon
    raise Exception('processing failed')
Exception: processing failed
2019-08-23 09:29:59,178 ERROR [proces_notas_daemon][MainThread] processing failed
Traceback (most recent call last):
  File "/var/projects/notas/venv/local/lib/python2.7/site-packages/oe_daemonutils/controller.py", line 124, in run
    self._subprocess_daemon()
  File "/var/projects/notas/venv/local/lib/python2.7/site-packages/oe_daemonutils/controller.py", line 115, in _subprocess_daemon
    raise Exception('processing failed')
Exception: processing failed
2019-08-23 09:29:59,178 WARNI [proces_notas_daemon][MainThread] daemon stopped
2019-08-23 09:29:59,178 WARNI [proces_notas_daemon][MainThread] daemon stopped
Traceback (most recent call last):
  File "/var/projects/notas/scripts/proces_notas_daemon.py", line 36, in <module>
    main()
  File "/var/projects/notas/scripts/proces_notas_daemon.py", line 32, in main
    controller.run()
  File "/var/projects/notas/venv/local/lib/python2.7/site-packages/oe_daemonutils/controller.py", line 129, in run
    self._handle_unrecoverable_error(e)
  File "/var/projects/notas/venv/local/lib/python2.7/site-packages/oe_daemonutils/controller.py", line 139, in _handle_unrecoverable_error
    raise ex
Exception: processing failed
```

**Comment by axd1967** [comment]
seen in https://github.com/OnroerendErfgoed/scripts/issues/317#issuecomment-524890221

**Comment by Wim-De-Clercq** [comment]
Dit zal zo goed als onmogelijk zijn om voor ons te tracken of op te lossen.

Wat wij sturen als message is gewoon een string (hardcoded string met wat variables erin geformat) en dit is correct. De error suggest dat we bij het communiceren met de SMTP server geen `\r\n` als laatste deel van de message hebben gestuurd. Maar:

1) dit is python library code
2) het is volgens die code gewoon onmogelijk om geen '\r\n' te hebben als laatste deel. https://github.com/python/cpython/blob/9978a9553b5273ca8f55c4130383c4ee151fbe2a/Lib/smtplib.py#L507-L511

Verder is dit ook niet reproduceerbaar.
Als het uitzonderlijk vaak zou voorkomen dan zouden we op het smtp object `.set_debuglevel(2)` kunnen zetten. En alles wordt dan ge**print** (niet gelogd, print naar stderr). En dan is er output zoals. (Dit is een persoonlijke mail server met TLS, de output zal dus iets anders zijn want er is geen TLS in onze code)

```
send: 'ehlo [127.0.1.1]\r\n'
reply: '250-ak47\r\n'
reply: '250-AUTH PLAIN LOGIN\r\n'
reply: '250-SIZE 52428800\r\n'
reply: '250-8BITMIME\r\n'
reply: '250-ENHANCEDSTATUSCODES\r\n'
reply: '250-SMTPUTF8\r\n'
reply: '250 STARTTLS\r\n'
reply: retcode (250); Msg: ak47
AUTH PLAIN LOGIN
SIZE 52428800
8BITMIME
ENHANCEDSTATUSCODES
SMTPUTF8
STARTTLS
send: 'AUTH PLAIN AHBvc3RtYXN0ZXJAc2FuZGJveGJlZjY5YTRjMzc3YjRhOWI4OWI5MzRjNzg5ZDIxNzU0Lm1haWxndW4ub3JnADBjZjcxNjJhNDExODA1NDgwNjExM2YxMzBiYjA2ODU2LWMyN2JmNjcyLWM5ZTFhOWFm\r\n'
reply: '235 2.0.0 OK\r\n'
reply: retcode (235); Msg: 2.0.0 OK
send: 'mail FROM:<wim@wim.wim> size=1405\r\n'
reply: '250 Sender address accepted\r\n'
reply: retcode (250); Msg: Sender address accepted
send: 'rcpt TO:<my@email.com>\r\n'
reply: '250 Recipient address accepted\r\n'
reply: retcode (250); Msg: Recipient address accepted
send: 'data\r\n'
reply: '354 Continue\r\n'
reply: retcode (354); Msg: Continue
data: (354, 'Continue')
send: 'Content-Type: multipart/alternative;\r\n boundary="===============7681798138018473064=="\r\nMIME-Version: 1.0\r\nSubject: =?utf-8?q?test?=\r\nFrom: wim@wim.wim\r\nTo: my@email.com\r\n\r\n--===============7681798138018473064==\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset="utf-8"\r\nContent-Transfer-Encoding: base64\r\n\r\nQmVzdGUsCgpPcCAxOTkwLzA2LzE3IHdlcmQgb3AgaGV0IGFyY2hlb2xvZ2llcG9ydGFhbCBlZW4g\r\nbm90YSBpbmdlZGllbmQgdm9vciBoZXQgcHJvamVjdCBodHRwczovL2dvb2dsZS5iZSBiaW5uZW4g\r\ndXcgZ2VtZWVudGUsIG5sLiBhYXJ0c2VsYWFyLiBVIGthbiBkZXplIHJhYWRwbGVnZW4gb3AgaHR0\r\ncHM6Ly9nb29nbGUuYmUvbWFuYWdlLiBEZSB1aXRlcnN0ZSBkYXR1bSB3YWFyb3AgdXcgZ2VtZWVu\r\ndGUgZWVuIGJlc2xpc3NpbmcgKGFrdGVuYW1lLCBnZWVuIGFrdGVuYW1lIG9mIGFrdGVuYW1lIG1l\r\ndCB2b29yd2FhcmRlbikgbW9ldCBuZW1lbiBvdmVyIGRlemUgbm90YSBpcyAyMDIwLzEwLzE2LiBJ\r\nbmRpZW4gdXcgZ2VtZWVudGUgZ2VlbiBiZXNsaXNzaW5nIGhlZWZ0IGdlbm9tZW4gb3AgMjAyMC8x\r\nMC8xNiBiZXRla2VudCBkaXQgYXV0b21hdGlzY2ggZGF0IHZhbiBkZSBub3RhIHZvb3IgaGV0IHBy\r\nb2plY3QgaHR0cHM6Ly9nb29nbGUuYmUgd29yZHQgYWt0ZSBnZW5vbWVuLiBVdyBnZW1lZW50ZSBi\r\nZXpvcmd0IGRlIGdlbW90aXZlZXJkZSBiZXNsaXNzaW5nIHBlciBiZXZlaWxpZ2RlIHplbmRpbmcg\r\nYWFuIGRlIGluaXRpYXRpZWZuZW1lciBlbiBkZSBlcmtlbmRlIGFyY2hlb2xvb2cuCgpNZXQgdnJp\r\nZW5kZWxpamtlIGdyb2V0ZW4sCgogICAgCgogICAgT25yb2VyZW5kIEVyZmdvZWQKCiAgICBIZXJt\r\nYW4gVGVpcmxpbmNrZ2Vib3V3ICB8ICBIYXZlbmxhYW4gODggYnVzIDUgIHwgIDEwMDAgQnJ1c3Nl\r\nbAoKICAgIHd3dy5vbnJvZXJlbmRlcmZnb2VkLmJlCgogICAgCgogICAg\r\n\r\n--===============7681798138018473064==--\r\n.\r\n'
reply: '250 Great success\r\n'
reply: retcode (250); Msg: Great success
data: (250, 'Great success')
```
Die ons dan hopelijk verder wijst.

In ieder geval denk ik toch eerder aan een hickup in de connectie of fout langs de SMTP server dan iets dan hier op te lossen valt.
